WebApplication/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Common;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using WebApplication.Models;

namespace WebApplication.Controllers
{	
	public class AboutController : TeddyNewsController
	{
		private static log4net.ILog log = log4net.LogManager.GetLogger(typeof(AboutController));


		public ActionResult Index()
		{			
			return View();
		}

		[HttpPost]
		public async Task<ActionResult> Start()
		{
			await this.tryCreateAccount();
			return RedirectToAction("Index", "Article");
		}

		[HttpPost]
		public async Task<ActionResult> DeleteCookie()
		{
			
			await this.deleteAccountCookie();
			return RedirectToAction("Index");
		}

		
		
	}
}

WebApplication/Views/About/Index.cshtml
@{
	ViewBag.Title = "Teddy News";
}
<br />
<div class="article-details-container">
	
	<h1>About Teddy News</h1>
	<p>TeddyNews is an news aggregator. Simply visit the proposed articles or <i>Skip</i> it.</p>
	<p>
		@using (Html.BeginForm("Start", "About", FormMethod.Post, new { @class = "form-inline", role = "form" }))
		{
			@Html.AntiForgeryToken()
			<input type="submit" value="Let's go" class="btn btn-primary btn-lg" title="" />
		}
		
	</p>

	<h1>Teddy News account</h1>
	<p>If you use more than one computer, you may be interrested to create an account. It will allow you to have only new articles when you use different devices.</p>
	<p>
		@using (Html.BeginForm("Login", "Account", FormMethod.Post, new { @class = "form-inline", role = "form" }))
		{
			@Html.AntiForgeryToken()
			<input type="submit" value="Login" class="btn btn-primary btn-lg" title="Login" />
		}
	
		@using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-inline", role = "form" }))
		{
			@Html.AntiForgeryToken()
			<input type="submit" value="Create account" class="btn btn-primary btn-lg" title="Create account" />
		}
	</p>

	<h1>Cookie notice</h1>
	<p>This web site use a cookie to remember what you have visited and recomand articles according to your taste.</p>
	<p>By using TeddyNews, you accept such use.</p>

	<h1>Delete cookie</h1>
	<p>Delete the TeddyNews cookie to erase your history and start a fresh news session.</p>
	<p>
		@using (Html.BeginForm("DeleteCookie", "About", FormMethod.Post, new { @class = "form-inline", role = "form" }))
		{
			@Html.AntiForgeryToken()
			<input type="submit" value="Delete cookie" class="btn btn-primary btn-lg" title="Delete cookie" />
		}
	</p>
	
</div>